on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: ruby/setup-ruby@v1.97.0
        with:
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec lib
